import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import './material-symbols.css';
import Header from '@/components/Header/Header';
import { getUser } from '@/utils/supabase/getUser';

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang='en'>
      <body className={`${spaceGrotesk.variable}`}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
