name: CI Pipeline

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug directory contents
              run: ls -l cosmic-dashboard/

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: cosmic-dashboard/package-lock.json

            - name: Install dependencies
              working-directory: ./cosmic-dashboard
              run: npm ci

            - name: Run ESLint
              working-directory: ./cosmic-dashboard
              run: npm run lint

            - name: Run TypeScript type-check
              working-directory: ./cosmic-dashboard
              run: npm run type-check

    test-unit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug directory contents
              run: ls -l cosmic-dashboard/

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: cosmic-dashboard/package-lock.json

            - name: Install dependencies
              working-directory: ./cosmic-dashboard
              run: npm ci

            - name: Run Jest tests
              working-directory: ./cosmic-dashboard
              run: npm run test

    test-e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug directory contents
              run: ls -l cosmic-dashboard/

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: cosmic-dashboard/package-lock.json

            - name: Install dependencies
              working-directory: ./cosmic-dashboard
              run: npm ci

            - name: Install Playwright browsers
              working-directory: ./cosmic-dashboard
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              working-directory: ./cosmic-dashboard
              run: |
                  npm run test:e2e
                  npm run pw:report

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: cosmic-dashboard/playwright-report/
                  retention-days: 30
